# Generated by Django 4.1.7 on 2023-02-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, to='games.tag', verbose_name='Теги'),
        ),
    ]
