# Generated by Django 4.1.7 on 2023-02-18 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0006_alter_game_options_game_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='age_limit',
            field=models.CharField(choices=[('Информационная продукция для детей, не достигших возраста шести лет', '0+'), ('Информационная продукция для детей, достигших возраста шести лет', '6+'), ('Информационная продукция для детей, достигших возраста двенадцати лет', '12+'), ('Информационная продукция для детей, достигших возраста шестнадцати лет', '16+'), ('Информация, запрещённая для распространения среди детей', '18+')], max_length=70, verbose_name='Возрастной ценз'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_score', to='games.game'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
