# Generated by Django 4.1.7 on 2023-02-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_game_age_limit_alter_rating_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
    ]
